# Generated by Django 3.2.7 on 2025-03-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_package_packageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
    ]
