# Generated by Django 3.2.7 on 2025-03-01 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20250301_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
