# Generated by Django 3.2.7 on 2025-03-05 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.creditcardpayment'),
        ),
    ]
