# Generated by Django 3.2.7 on 2025-03-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_bookings_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vacation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
