# Generated by Django 3.2.7 on 2025-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
