# Generated by Django 3.2.7 on 2026-03-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_chatbotqa_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='num_persons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
