# Generated by Django 3.2.7 on 2026-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images/'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
