# Generated by Django 3.2.7 on 2026-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20260320_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='room_type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default='Non-AC', max_length=20),
        ),
    ]
