# Generated by Django 3.2.7 on 2026-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20260320_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
