# Generated by Django 3.2.7 on 2026-03-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_accommodation_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookings',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookings',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
